# .github/workflows/test-schedule.yml
name: Schedule Test

on:
  schedule:
    - cron: '*/2 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "ðŸ‘‹ Hello from scheduled job"
